"use client";

import { useMemo, useState } from "react";
import JSZip from "jszip";
import * as XLSX from "xlsx";
import type { AutomationArtifact, GenerationResult, ManualTestCase, OutputType } from "@/lib/schema";

const example = "A visitor can create an account with a valid email and password. Email is required. Password must be 8 to 64 characters. If registration fails, show a clear error and allow the visitor to try again.";
const outputs: { key: OutputType; label: string; note: string }[] = [
  { key: "manual", label: "Manual cases", note: "Steps, expected results, priority" },
  { key: "playwright_ui", label: "Playwright UI", note: "Browser test templates" },
  { key: "playwright_api", label: "Playwright API", note: "Request test templates" }
];
function download(data: BlobPart, name: string, type: string) { const url = URL.createObjectURL(new Blob([data], { type })); const a = Object.assign(document.createElement("a"), { href: url, download: name }); a.click(); setTimeout(() => URL.revokeObjectURL(url), 500); }
function slug(value: string) { return (value || "test-suite").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "test-suite"; }

export default function Home() {
  const [requirements, setRequirements] = useState(""); const [feature, setFeature] = useState(""); const [depth, setDepth] = useState("standard");
  const [selectedOutputs, setSelectedOutputs] = useState<OutputType[]>(["manual", "playwright_ui", "playwright_api"]); const [file, setFile] = useState<File | null>(null);
  const [result, setResult] = useState<GenerationResult | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const [cases, setCases] = useState<ManualTestCase[]>([]); const [artifacts, setArtifacts] = useState<AutomationArtifact[]>([]);
  const selectedCases = useMemo(() => cases, [cases]);
  const updateCase = (index: number, key: keyof ManualTestCase, value: string) => setCases(current => current.map((item, i) => i === index ? { ...item, [key]: key === "steps" || key === "preconditions" || key === "sourceRequirements" ? value.split("\n").filter(Boolean) : value } : item));
  async function generate(event: React.FormEvent) {
    event.preventDefault(); setError(""); if (!requirements.trim() && !file) { setError("Add requirements or upload a document."); return; }
    if (!selectedOutputs.length) { setError("Choose at least one output type."); return; }
    setLoading(true); try { const form = new FormData(); form.set("requirements", requirements); form.set("feature", feature); form.set("depth", depth); form.set("outputs", selectedOutputs.join(",")); if (file) form.set("file", file);
      const response = await fetch("/api/generate", { method: "POST", body: form }); const json = await response.json(); if (!response.ok) throw new Error(json.error || "Generation failed.");
      setResult(json.result); setCases(json.result.manualCases); setArtifacts(json.result.automationArtifacts);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Generation failed."); } finally { setLoading(false); }
  }
  function exportCsv() { const rows = cases.map(c => ({ "Test Case ID": c.id, Feature: c.feature, Title: c.title, Description: c.description, Preconditions: c.preconditions.join("\n"), Priority: c.priority, Category: c.category, Steps: c.steps.map((s, i) => `${i + 1}. ${s}`).join("\n"), "Expected Result": c.expectedResult, "Source Requirement": c.sourceRequirements.join("\n") })); const csv = XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(rows)); download("\ufeff" + csv, `${slug(feature)}-test-cases.csv`, "text/csv;charset=utf-8"); }
  function exportXlsx() { const rows = cases.map(c => ({ "Test Case ID": c.id, Feature: c.feature, Title: c.title, Description: c.description, Preconditions: c.preconditions.join("\n"), Priority: c.priority, Category: c.category, Steps: c.steps.map((s, i) => `${i + 1}. ${s}`).join("\n"), "Expected Result": c.expectedResult, "Source Requirement": c.sourceRequirements.join("\n") })); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), "Test Cases"); XLSX.writeFile(wb, `${slug(feature)}-test-cases.xlsx`); }
  async function exportZip() { const zip = new JSZip(); zip.file("package.json", JSON.stringify({ private: true, scripts: { test: "playwright test" }, devDependencies: { "@playwright/test": "latest" } }, null, 2)); zip.file("playwright.config.ts", "import { defineConfig } from '@playwright/test';\nexport default defineConfig({ use: { baseURL: process.env.BASE_URL } });\n"); zip.file("README.md", "# Generated Playwright tests\n\nInstall dependencies with `npm install`, set `BASE_URL` and any TODO configuration, then run `npm test`. Review all generated assumptions before use.\n"); artifacts.forEach(a => zip.file(`tests/${a.type === "playwright_ui" ? "ui" : "api"}/${a.filename.replace(/^.*\//, "")}`, a.source)); download(await zip.generateAsync({ type: "blob" }), `${slug(feature)}-playwright-tests.zip`, "application/zip"); }
  return <main><section className="hero"><p className="eyebrow">TEST DESIGN AGENT</p><h1>Requirements in.<br /><em>Test confidence out.</em></h1><p>Generate editable manual cases and Playwright-ready test artifacts—without exposing your API key in the browser.</p></section>
    <form className="panel intake" onSubmit={generate}><div className="field-grid"><label>Feature or module<input value={feature} onChange={e => setFeature(e.target.value)} placeholder="e.g. Account registration" /></label><label>Test depth<select value={depth} onChange={e => setDepth(e.target.value)}><option value="standard">Standard</option><option value="thorough">Thorough</option></select></label></div><label>Requirements<textarea value={requirements} onChange={e => setRequirements(e.target.value)} placeholder="Paste a user story, specification, or acceptance criteria…" rows={8} /><span>{requirements.length.toLocaleString()} / 25,000 characters</span></label><div className="row"><label className="upload">Attach a document<input type="file" accept=".txt,.md,.docx,.pdf" onChange={e => setFile(e.target.files?.[0] || null)} /><strong>{file ? file.name : "TXT, MD, DOCX or text PDF · max 5 MB"}</strong></label><button type="button" className="link" onClick={() => setRequirements(example)}>Use example</button></div><fieldset><legend>Generate</legend><div className="outputs">{outputs.map(output => <label className="choice" key={output.key}><input type="checkbox" checked={selectedOutputs.includes(output.key)} onChange={() => setSelectedOutputs(current => current.includes(output.key) ? current.filter(x => x !== output.key) : [...current, output.key])} /><span><b>{output.label}</b><small>{output.note}</small></span></label>)}</div></fieldset>{error && <p className="error" role="alert">{error}</p>}<button className="primary" disabled={loading}>{loading ? "Designing your test suite…" : "Generate test suite"}</button></form>
    {result && <section className="results"><header><div><p className="eyebrow">REVIEW OUTPUT</p><h2>{result.requirementSummary}</h2></div><div className="exports"><button onClick={exportCsv} disabled={!cases.length}>CSV</button><button onClick={exportXlsx} disabled={!cases.length}>Excel</button><button onClick={exportZip} disabled={!artifacts.length}>Playwright ZIP</button></div></header>{(result.assumptions.length > 0 || result.ambiguities.length > 0) && <aside><b>Review before use</b>{[...result.assumptions, ...result.ambiguities].map((item, i) => <p key={i}>{item}</p>)}</aside>}<h3>Manual test cases <span>{cases.length}</span></h3><div className="cards">{cases.map((item, index) => <article className="case" key={item.id}><div className="case-head"><b>{item.id}</b><span>{item.priority}</span><button type="button" onClick={() => setCases(current => current.filter((_, i) => i !== index))}>Remove</button></div><label>Title<input value={item.title} onChange={e => updateCase(index, "title", e.target.value)} /></label><div className="two"><label>Category<input value={item.category} onChange={e => updateCase(index, "category", e.target.value)} /></label><label>Expected result<textarea value={item.expectedResult} onChange={e => updateCase(index, "expectedResult", e.target.value)} /></label></div><label>Steps <textarea value={item.steps.join("\n")} onChange={e => updateCase(index, "steps", e.target.value)} /></label></article>)}</div><h3>Automation artifacts <span>{artifacts.length}</span></h3><div className="artifacts">{artifacts.map((item, index) => <article key={item.id}><div><b>{item.filename}</b><small>{item.type.replace("_", " ")} · {item.title}</small></div><textarea aria-label={item.filename} value={item.source} onChange={e => setArtifacts(current => current.map((a, i) => i === index ? { ...a, source: e.target.value } : a))} rows={14} /></article>)}</div></section>}</main>;
}
